Add env variable with port number
fcsmJS/expressjs-getting-started pull request #8
Opened 2021-04-05 23:50 UTC by fcsmJS

2021-04-06 18:43 UTC, kicumkicum requested changes

2021-04-06 18:43 UTC, kicumkicum commented on hello-world/app.js
> +const dotenv = require('dotenv');
Так же как и в другом. Подключение зависимостей до основного кода

2021-04-07 06:56 UTC, kicumkicum commented
Когда какой-то ПР будет закрывать ишью, то в описании к ПРу пиши fix or fixes #6 . Так ишья будет закрыта автоматически, когда ПР будет смержен

2021-04-07 21:22 UTC, fcsmJS commented
fixes  #6

2021-04-08 10:29 UTC, kicumkicum approved these changes

2021-04-08 10:29 UTC, merged